package structural.flyweight;

/**
 * FlyweightMain 클래스는 단순히 인수로 주어진 문자열을 바탕으로
 * BigString 인스턴스를 만들고 이를 표시 합니다.
 */
public class FlyweightMain {
    public static void main(String[] args) {
        if(args.length == 0) {
            System.out.println("Usage: java java digits");
            System.out.println("Example: java FlyweightMain.java 1212123");
        }
        BigString bs = new BigString(args[0]);
        bs.print();
    }
}
/*
출력 결과
.....##........
..######......
......##.......
......##.......
......##.......
......##.......
...########....

....######.....
..##......##...
..........##...
......#####....
.....##........
...##..........
..##########...

.....##........
..######......
......##.......
......##.......
......##.......
......##.......
...########....

....######.....
..##......##...
..........##...
......#####....
.....##........
...##..........
..##########...

... 생략
 */